prime_num = int(input("첫 번째 정수를 입력하시오: "))
inferior_num = int(input("두 번째 정수를 입력하시오: "))
print(f"{prime_num} + {inferior_num} = {prime_num+inferior_num}")
print(f"{prime_num} - {inferior_num} = {prime_num-inferior_num}")
print(f"{prime_num} * {inferior_num} = {prime_num*inferior_num}")
print(f"{prime_num} / {inferior_num} = {prime_num/inferior_num}")